// Code generated by protoc-gen-go. DO NOT EDIT.
// source: logvault.proto

/*
Package logvault is a generated protocol buffer package.

It is generated from these files:
	logvault.proto

It has these top-level messages:
	IngestRequest
	IngestResponse
*/
package logvault

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IngestRequest struct {
	Log      string `protobuf:"bytes,1,opt,name=log" json:"log,omitempty"`
	Prefix   string `protobuf:"bytes,2,opt,name=prefix" json:"prefix,omitempty"`
	Hostname string `protobuf:"bytes,3,opt,name=hostname" json:"hostname,omitempty"`
	Filename string `protobuf:"bytes,4,opt,name=filename" json:"filename,omitempty"`
}

func (m *IngestRequest) Reset()                    { *m = IngestRequest{} }
func (m *IngestRequest) String() string            { return proto.CompactTextString(m) }
func (*IngestRequest) ProtoMessage()               {}
func (*IngestRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *IngestRequest) GetLog() string {
	if m != nil {
		return m.Log
	}
	return ""
}

func (m *IngestRequest) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *IngestRequest) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *IngestRequest) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

type IngestResponse struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *IngestResponse) Reset()                    { *m = IngestResponse{} }
func (m *IngestResponse) String() string            { return proto.CompactTextString(m) }
func (*IngestResponse) ProtoMessage()               {}
func (*IngestResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *IngestResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*IngestRequest)(nil), "logvault.IngestRequest")
	proto.RegisterType((*IngestResponse)(nil), "logvault.IngestResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Logvault service

type LogvaultClient interface {
	IngestLog(ctx context.Context, in *IngestRequest, opts ...grpc.CallOption) (*IngestResponse, error)
}

type logvaultClient struct {
	cc *grpc.ClientConn
}

func NewLogvaultClient(cc *grpc.ClientConn) LogvaultClient {
	return &logvaultClient{cc}
}

func (c *logvaultClient) IngestLog(ctx context.Context, in *IngestRequest, opts ...grpc.CallOption) (*IngestResponse, error) {
	out := new(IngestResponse)
	err := grpc.Invoke(ctx, "/logvault.Logvault/IngestLog", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Logvault service

type LogvaultServer interface {
	IngestLog(context.Context, *IngestRequest) (*IngestResponse, error)
}

func RegisterLogvaultServer(s *grpc.Server, srv LogvaultServer) {
	s.RegisterService(&_Logvault_serviceDesc, srv)
}

func _Logvault_IngestLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogvaultServer).IngestLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logvault.Logvault/IngestLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogvaultServer).IngestLog(ctx, req.(*IngestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Logvault_serviceDesc = grpc.ServiceDesc{
	ServiceName: "logvault.Logvault",
	HandlerType: (*LogvaultServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IngestLog",
			Handler:    _Logvault_IngestLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logvault.proto",
}

func init() { proto.RegisterFile("logvault.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0xc1, 0x0a, 0x82, 0x40,
	0x10, 0x40, 0x33, 0x43, 0x74, 0x20, 0x89, 0x3d, 0xd4, 0xe2, 0x29, 0x3c, 0x79, 0xf2, 0x50, 0x3f,
	0xd0, 0x35, 0xf0, 0xe4, 0x1f, 0x18, 0xac, 0x9b, 0xb0, 0x39, 0xea, 0x8c, 0xd1, 0xe7, 0x87, 0xeb,
	0x2a, 0x44, 0xb7, 0x7d, 0xfb, 0x18, 0xde, 0x0c, 0xc4, 0x06, 0xf5, 0xbb, 0x1a, 0x0d, 0xe7, 0xdd,
	0x80, 0x8c, 0x22, 0x5c, 0x38, 0xed, 0x61, 0x7f, 0x6f, 0xb5, 0x22, 0x2e, 0x55, 0x3f, 0x2a, 0x62,
	0x71, 0x00, 0xdf, 0xa0, 0x96, 0xde, 0xd9, 0xcb, 0xa2, 0x72, 0x7a, 0x8a, 0x23, 0x04, 0xdd, 0xa0,
	0xea, 0xe6, 0x23, 0xb7, 0xf6, 0xd3, 0x91, 0x48, 0x20, 0x7c, 0x22, 0x71, 0x5b, 0xbd, 0x94, 0xf4,
	0xad, 0x59, 0x79, 0x72, 0x75, 0x63, 0x94, 0x75, 0xbb, 0xd9, 0x2d, 0x9c, 0x66, 0x10, 0x2f, 0x49,
	0xea, 0xb0, 0x25, 0x35, 0x15, 0x88, 0x2b, 0x1e, 0xc9, 0x65, 0x1d, 0x5d, 0x0a, 0x08, 0x0b, 0xb7,
	0xa8, 0xb8, 0x41, 0x34, 0x4f, 0x15, 0xa8, 0xc5, 0x29, 0x5f, 0x0f, 0xfa, 0xd9, 0x3e, 0x91, 0xff,
	0x62, 0x6e, 0xa4, 0x9b, 0x47, 0x60, 0x6f, 0xbf, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x76, 0x4b,
	0xe4, 0x7d, 0x0d, 0x01, 0x00, 0x00,
}
